---
apiVersion: v1
kind: Namespace
metadata:
  name: loadtest
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: load-test
  labels:
    name: load-test
  namespace: loadtest
spec:
  replicas: 2
  selector:
    matchLabels:
      name: load-test
  template:
    metadata:
      labels:
        name: load-test
    spec:
      containers:
      - name: load-test
        image: weaveworksdemos/load-test:0.1.1
        command: ["/bin/sh"]
        args: ["-c", "while true; do locust --host http://afe78853bc76c4299a177a96b0792e45-82359633.us-east-1.elb.amazonaws.com -f /config/locustfile.py --clients 1 --hatch-rate 5 --num-request 8 --no-web; done"]
      nodeSelector:
        beta.kubernetes.io/os: linux
